# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9367b4feaca882f5a6b77efd7bfcad442b0117ec1180eb788721f737cc7711248b8160e1282ec6a953edf9b12724fc4ff7c42ec111f5d16650596b9166aed52

test:
  secret_key_base: 698db6436f05bb43bf0f8e378410dac97e877fa5a3f037a51af2afd5a02dfaa2e2b9cc679e826222a0c1fc79ec1181ca0f8a4d5376cc1b10c9e2274788427e18

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
